import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import MainWrapper from '@/components/wrapper/main-wrapper'
import { RootWrapper } from '@/components/wrapper/root-wrapper'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ja'>
      <RootWrapper>
        <Header />
        <MainWrapper>{children}</MainWrapper>
      </RootWrapper>
    </html>
  )
}
